name: Publish NPM package

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust as needed
          registry-url: 'https://registry.npmjs.org'

      - name: Set Git user
        run: |
          git config --local user.name "Yariv"
          git config --local user.email "yarivluts@gmail.com"

      - name: Bump version and create tag
        run: |
          npm version patch
          git add .  # Add all modified files
          git commit -m "Bump version to [new version]"
          git push origin

      - name: Install dependencies
        run: npm ci

      - name: Build the package
        run: npm run build  # Replace with your build command

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
